# .github/workflows/deploy.yml

name: Build and Deploy Jekyll Site

on:
  # Trigger the workflow on pushes to the master branch
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Schedule for daily builds at 8:00 AM UTC
  schedule:
    - cron: '0 8 * * *'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v3

      - name: Setup Ruby and Jekyll ğŸ’
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Specify the Ruby version you need
          bundler-cache: true # Automatically runs bundle install

      - name: Build the site ğŸ—ï¸
        run: bundle exec jekyll build
        env:
          JEKYLL_ENV: production

      - name: Deploy to GitHub Pages ğŸš€
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site
          # If you are using a custom domain, add it here
          # cname: your.domain.com
